### ISSUE TITLE
关于WSS的配置问题

### ISSUE THREAD

**Issue by li-zheng-hao** [2881099/FreeIM#49]
目前已经把issue内关于wss配置的问题都看过一遍了，仍然出现如下问题（使用的是示例代码）：
![image](https://user-images.githubusercontent.com/22129824/194762269-dd3f2e42-0458-4d14-85bf-082af97cfb8b.png)

似乎是websocket连接没有建立，发送消息无法接收到

修改的配置项包括：
1. Webapi、ImServer添加`app.UseHttpsRedirection();`
2. `launchSettings.json`将`http`修改为`https`
3. `ImClient`60行将`ws`修改为`wss`

**Comment by li-zheng-hao** [comment]
[FreeIM-master.zip](https://github.com/2881099/FreeIM/files/9741834/FreeIM-master.zip)
这是修改后的代码

**Comment by 2881099** [comment]
wss 不能用ip访问，要用域名

并且浏览器跨域规则，必须是同域名，但是可以二级域名。

比如 webapi.baidu.com

imserver 服务器是 ws.baidu.com

**Comment by li-zheng-hao** [comment]
好的，明天有空我再修改试试

**Comment by li-zheng-hao** [comment]
暂时没空改，先关闭

**Comment by li-zheng-hao** [comment]
用域名配置完成后在chrome测试wss是正常的，在edge和360极速浏览器上测试连接不上，这个问题是浏览器的问题还是代码问题呢

![image](https://user-images.githubusercontent.com/22129824/195364654-850a95f0-5ec1-4f25-84c9-b0d54a859ef5.png)

测试代码如下：

[FreeIM-master-https-wss.zip](https://github.com/2881099/FreeIM/files/9765581/FreeIM-master-https-wss.zip)

**Comment by li-zheng-hao** [comment]
本地host添加配置：
```
127.0.0.1 sub.test.com
127.0.0.1 www.test.com  
```

**Comment by 2881099** [comment]
证书不安全，大概是这个原因，用真实的域名证书测试。

**Comment by li-zheng-hao** [comment]
有可能，暂时就不深究了

**Comment by 2881099** [comment]
安全策略，每种浏览器都不一样。
