### ISSUE TITLE
如何清理online表的无效数据?

### ISSUE THREAD

**Issue by dmhai** [2881099/FreeIM#52]
似乎是因为im服务器意外停止(或者其他原因)，客户端下线之后，server未能在online表删除对应记录，
重启Im服务器之后，出现很多假的在线用户，本想设置15s过期时间，然后用心跳不断延长过期来解决，
可online表无法单独设置每个clientId的过期时间

能否设计一个妥善的处理机制？

**Comment by 2881099** [comment]
refis.HDel($"{_redisPrefix}Online")

ImServer 启动时，做一下这个操作

**Comment by 2881099** [comment]
你可以用 keys *Online 查看对应的 key

**Comment by dmhai** [comment]
感谢回复，我再好好考虑下有没有其他思路。这个就结了
